# Generated by Django 3.2 on 2022-02-24 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0002_alter_service_servicedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='shopId',
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 6, 8, 59, 50039, tzinfo=utc)),
        ),
    ]
