# Generated by Django 3.2 on 2022-02-24 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0003_auto_20220224_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='shopId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 6, 38, 29, 504329, tzinfo=utc)),
        ),
    ]
