# Generated by Django 3.2 on 2022-04-08 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0005_auto_20220228_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imageFile',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 59, 41, 791024, tzinfo=utc)),
        ),
    ]
