# Generated by Django 3.2 on 2022-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0005_auto_20220222_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='nickname',
            field=models.CharField(max_length=80),
        ),
    ]
