# Generated by Django 3.2 on 2022-04-09 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0006_auto_20220408_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 9, 0, 0, 5, 591023, tzinfo=utc)),
        ),
    ]
