# Generated by Django 3.2 on 2022-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0006_auto_20220222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='nickname',
            field=models.TextField(max_length=50),
        ),
    ]
