# Generated by Django 3.2 on 2022-02-26 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0006_auto_20220226_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 3, 32, 2, 791033, tzinfo=utc)),
        ),
    ]
