# Generated by Django 3.2 on 2022-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0007_auto_20220222_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
