# Generated by Django 3.2 on 2022-04-11 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0007_alter_service_servicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 22, 11, 46, 267199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehiclenote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
