# Generated by Django 3.2 on 2022-02-26 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0007_alter_service_servicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 3, 33, 47, 623432, tzinfo=utc)),
        ),
    ]
