# Generated by Django 3.2 on 2022-02-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0008_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='warrantyUntil',
            field=models.DateField(blank=True, null=True),
        ),
    ]
