# Generated by Django 3.2 on 2022-04-13 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0008_auto_20220411_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 13, 10, 37, 36, 801630, tzinfo=utc)),
        ),
    ]
