# Generated by Django 3.2 on 2022-02-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0009_alter_vehicle_warrantyuntil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
