# Generated by Django 3.2 on 2022-04-27 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0009_auto_20220413_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-serviceDate']},
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 0, 46, 27, 787271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='shopId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warrantyUntil',
            field=models.DateField(blank=True, null=True),
        ),
    ]
