# Generated by Django 3.2 on 2022-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0010_rename_image_url_vehicle_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
    ]
