# Generated by Django 3.2.13 on 2022-04-29 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0010_auto_20220427_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 22, 5, 39, 271310, tzinfo=utc)),
        ),
    ]
