# Generated by Django 3.2 on 2022-02-26 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0010_auto_20220226_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 2, 26, 20, 8, 56, 902125, tzinfo=utc)),
        ),
    ]
