# Generated by Django 3.2 on 2022-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0011_alter_vehicle_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isWarranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default='February 23, 2022'),
        ),
    ]
