# Generated by Django 3.2 on 2022-05-02 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0011_alter_service_servicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 9, 24, 31, 585124, tzinfo=utc)),
        ),
    ]
