# Generated by Django 3.2 on 2022-02-28 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0012_alter_service_servicedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclenote',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.datetime(2022, 2, 28, 5, 21, 53, 86264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehiclenote',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garage_backend.vehicle'),
        ),
    ]
