# Generated by Django 3.2 on 2022-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0012_auto_20220223_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='warrantyUntil',
            field=models.DateField(null=True),
        ),
    ]
