# Generated by Django 3.2 on 2022-02-23 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0013_alter_vehicle_warrantyuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDate',
            field=models.DateField(default=datetime.date(2022, 2, 23)),
        ),
    ]
