# Generated by Django 3.2 on 2022-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0014_alter_service_servicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
