# Generated by Django 3.2 on 2022-02-23 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0017_alter_service_servicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='shopId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_users', related_query_name='vehicle_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('contact', models.TextField(max_length=12, null=True)),
                ('address', models.TextField(null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='shop_users', related_query_name='shop_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
