# Generated by Django 3.2 on 2022-02-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0018_auto_20220223_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_vehicles', related_query_name='service_vehicle', to='garage_backend.vehicle'),
        ),
    ]
