# Generated by Django 3.2 on 2022-02-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_backend', '0019_alter_service_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextAppointment', models.DateTimeField(null=True)),
                ('lfTire', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('rfTire', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('lrTire', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('rrTire', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('fBrake', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('rBrake', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('note', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='note_vehicles', related_query_name='note_vehicle', to='garage_backend.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
